INSERT OVERWRITE TABLE REGION
SELECT * FROM REGION_F;

INSERT OVERWRITE TABLE LINEITEM
SELECT * FROM LINEITEM_F;

INSERT OVERWRITE TABLE ORDERS
SELECT * FROM ORDERS_F;

INSERT OVERWRITE TABLE PARTSUPP
SELECT * FROM PARTSUPP_F;

INSERT OVERWRITE TABLE CUSTOMER
SELECT * FROM CUSTOMER_F;

INSERT OVERWRITE TABLE SUPPLIER
SELECT * FROM SUPPLIER_F;

INSERT OVERWRITE TABLE NATION
SELECT * FROM NATION_F;

INSERT OVERWRITE TABLE PART
SELECT * FROM PART_F;

ANALYZE TABLE REGION COMPUTE STATISTICS;
ANALYZE TABLE LINEITEM COMPUTE STATISTICS;
ANALYZE TABLE ORDERS COMPUTE STATISTICS;
ANALYZE TABLE PARTSUPP COMPUTE STATISTICS;
ANALYZE TABLE CUSTOMER COMPUTE STATISTICS;
ANALYZE TABLE SUPPLIER COMPUTE STATISTICS;
ANALYZE TABLE NATION COMPUTE STATISTICS;
ANALYZE TABLE PART COMPUTE STATISTICS;
