DROP TABLE IF EXISTS LINEITEM_F;
DROP TABLE IF EXISTS ORDERS_F;
DROP TABLE IF EXISTS PARTSUPP_F;
DROP TABLE IF EXISTS CUSTOMER_F;
DROP TABLE IF EXISTS SUPPLIER_F;
DROP TABLE IF EXISTS NATION_F;
DROP TABLE IF EXISTS REGION_F;
DROP TABLE IF EXISTS PART_F;

CREATE TABLE REGION_F (
    R_REGIONKEY  INT,
    R_NAME       CHAR(25),
    R_COMMENT    VARCHAR(152)
    )
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/mirko/tpch100data/region'
;


CREATE EXTERNAL TABLE NATION_F (
    N_NATIONKEY  INT,
    N_NAME CHAR(25),
    N_REGIONKEY  INT,
    N_COMMENT    VARCHAR(152)
    )
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/mirko/tpch100data/nation'
;


CREATE EXTERNAL TABLE PART_F (
    P_PARTKEY     INT,
    P_NAME        VARCHAR(55),
    P_MFGR        CHAR(25),
    P_BRAND       CHAR(10),
    P_TYPE        VARCHAR(25),
    P_SIZE        INT,
    P_CONTAINER   CHAR(10),
    P_RETAILPRICE DOUBLE,
    P_COMMENT     VARCHAR(23)
    )
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/mirko/tpch100data/part'
;

CREATE EXTERNAL TABLE SUPPLIER_F (
    S_SUPPKEY     INT,
    S_NAME        CHAR(25),
    S_ADDRESS     VARCHAR(40),
    S_NATIONKEY   INT,
    S_PHONE       CHAR(15),
    S_ACCTBAL     DOUBLE,
    S_COMMENT     VARCHAR(101)
    )
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/mirko/tpch100data/supplier'
;

CREATE EXTERNAL TABLE PARTSUPP_F (
    PS_PARTKEY     INT,
    PS_SUPPKEY     INT,
    PS_AVAILQTY    INT,
    PS_SUPPLYCOST  DOUBLE,
    PS_COMMENT     VARCHAR (199)
    )
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/mirko/tpch100data/partsupp'
;

CREATE EXTERNAL TABLE CUSTOMER_F (
    C_CUSTKEY     INT,
    C_NAME        VARCHAR(25),
    C_ADDRESS     VARCHAR(40),
    C_NATIONKEY   INT,
    C_PHONE       CHAR(15),
    C_ACCTBAL     DOUBLE  ,
    C_MKTSEGMENT  CHAR(10),
    C_COMMENT     VARCHAR(117)
    )
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/mirko/tpch100data/customer'
;

CREATE EXTERNAL TABLE ORDERS_F (
    O_ORDERKEY       BIGINT,
    O_CUSTKEY        INT,
    O_ORDERSTATUS    CHAR(1),
    O_TOTALPRICE     DOUBLE,
    O_ORDERDATE      DATE,
    O_ORDERPRIORITY  CHAR(15),
    O_CLERK          CHAR(15),
    O_SHIPPRIORITY   INT,
    O_COMMENT        VARCHAR(79)
    )
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/mirko/tpch100data/orders'
;

CREATE EXTERNAL TABLE LINEITEM_F (
    L_ORDERKEY    BIGINT,
    L_PARTKEY     INT,
    L_SUPPKEY     INT,
    L_LINENUMBER  INT,
    L_QUANTITY    DOUBLE,
    L_EXTENDEDPRICE  DOUBLE,
    L_DISCOUNT    DOUBLE,
    L_TAX         DOUBLE,
    L_RETURNFLAG  CHAR(1),
    L_LINESTATUS  CHAR(1),
    L_SHIPDATE    DATE,
    L_COMMITDATE  DATE,
    L_RECEIPTDATE DATE,
    L_SHIPINSTRUCT CHAR(25),
    L_SHIPMODE     CHAR(10),
    L_COMMENT      VARCHAR(44)
    )
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/mirko/tpch100data/lineitem'
;

