INSERT OVERWRITE TABLE REGION
SELECT * FROM REGION_F;

INSERT OVERWRITE TABLE LINEITEM
SELECT * FROM LINEITEM_F;

INSERT OVERWRITE TABLE ORDERS
SELECT * FROM ORDERS_F;

INSERT OVERWRITE TABLE PARTSUPP
SELECT * FROM PARTSUPP_F;

INSERT OVERWRITE TABLE CUSTOMER
SELECT * FROM CUSTOMER_F;

INSERT OVERWRITE TABLE SUPPLIER
SELECT * FROM SUPPLIER_F;

INSERT OVERWRITE TABLE NATION
SELECT * FROM NATION_F;

INSERT OVERWRITE TABLE PART
SELECT * FROM PART_F;

COMPUTE STATS ORDERS;
COMPUTE STATS PARTSUPP;
COMPUTE STATS CUSTOMER;
COMPUTE STATS SUPPLIER;
COMPUTE STATS NATION;
COMPUTE STATS REGION;
COMPUTE STATS PART;
COMPUTE STATS LINEITEM;
