INSERT OVERWRITE TABLE TPCH.REGION
SELECT * FROM REGION_F;

INSERT OVERWRITE TABLE TPCH.LINEITEM
SELECT * FROM LINEITEM_F;

INSERT OVERWRITE TABLE TPCH.ORDERS
SELECT * FROM ORDERS_F;

INSERT OVERWRITE TABLE TPCH.PARTSUPP
SELECT * FROM PARTSUPP_F;

INSERT OVERWRITE TABLE TPCH.CUSTOMER
SELECT * FROM CUSTOMER_F;

INSERT OVERWRITE TABLE TPCH.SUPPLIER
SELECT * FROM SUPPLIER_F;

INSERT OVERWRITE TABLE TPCH.NATION
SELECT * FROM NATION_F;

INSERT OVERWRITE TABLE TPCH.PART
SELECT * FROM PART_F;

COMPUTE STATS TPCH.ORDERS;
COMPUTE STATS TPCH.PARTSUPP;
COMPUTE STATS TPCH.CUSTOMER;
COMPUTE STATS TPCH.SUPPLIER;
COMPUTE STATS TPCH.NATION;
COMPUTE STATS TPCH.REGION;
COMPUTE STATS TPCH.PART;
COMPUTE STATS TPCH.LINEITEM;
