impala-shell -f 1.sql
impala-shell -f 2.sql
impala-shell -f 3.sql
impala-shell -f 4.sql
impala-shell -f 5.sql
impala-shell -f 6.sql
impala-shell -f 7.sql
impala-shell -f 8.sql
impala-shell -f 9.sql
impala-shell -f 10.sql
impala-shell -f 11.sql
impala-shell -f 12.sql
impala-shell -f 13.sql
impala-shell -f 14.sql
impala-shell -f 15.sql
impala-shell -f 16.sql
impala-shell -f 17.sql
impala-shell -f 18.sql
impala-shell -f 19.sql
impala-shell -f 20.sql
impala-shell -f 21.sql
impala-shell -f 22.sql